{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "intel-gpu-resource-driver.fullname" . }}-rolebinding
  namespace: {{ include "intel-gpu-resource-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "intel-gpu-resource-driver.serviceAccountName" . }}
  namespace: {{ include "intel-gpu-resource-driver.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "intel-gpu-resource-driver.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- if and .Values.alertWebhook.enabled .Values.alertWebhook.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-gpu-alert-webhook-role-binding
  namespace: {{ include "intel-gpu-resource-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: intel-gpu-alert-webhook-service-account
  namespace: intel-gpu-resource-driver
roleRef:
  kind: ClusterRole
  name: intel-gpu-alert-webhook-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}